'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Localization
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Resource_Struttura
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Autorinomina.Resource_Struttura", GetType(Resource_Struttura).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Year.
        '''</summary>
        Public Shared ReadOnly Property AR_Anno() As String
            Get
                Return ResourceManager.GetString("AR_Anno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Date.
        '''</summary>
        Public Shared ReadOnly Property AR_Data() As String
            Get
                Return ResourceManager.GetString("AR_Data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Filtered filename.
        '''</summary>
        Public Shared ReadOnly Property AR_NomeDelFile() As String
            Get
                Return ResourceManager.GetString("AR_NomeDelFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Numbering.
        '''</summary>
        Public Shared ReadOnly Property AR_Numerazione() As String
            Get
                Return ResourceManager.GetString("AR_Numerazione", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Regular expression.
        '''</summary>
        Public Shared ReadOnly Property AR_RegexPattern() As String
            Get
                Return ResourceManager.GetString("AR_RegexPattern", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Episode title.
        '''</summary>
        Public Shared ReadOnly Property AR_TitoloEpisodio() As String
            Get
                Return ResourceManager.GetString("AR_TitoloEpisodio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a TV show title.
        '''</summary>
        Public Shared ReadOnly Property AR_TitoloSerieTv() As String
            Get
                Return ResourceManager.GetString("AR_TitoloSerieTv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Music.
        '''</summary>
        Public Shared ReadOnly Property CATEGORIA_audio() As String
            Get
                Return ResourceManager.GetString("CATEGORIA_audio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a General.
        '''</summary>
        Public Shared ReadOnly Property CATEGORIA_generica() As String
            Get
                Return ResourceManager.GetString("CATEGORIA_generica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Images.
        '''</summary>
        Public Shared ReadOnly Property CATEGORIA_immagini() As String
            Get
                Return ResourceManager.GetString("CATEGORIA_immagini", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a TV series.
        '''</summary>
        Public Shared ReadOnly Property CATEGORIA_serietv() As String
            Get
                Return ResourceManager.GetString("CATEGORIA_serietv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Category.
        '''</summary>
        Public Shared ReadOnly Property CATEGORIA_titolo() As String
            Get
                Return ResourceManager.GetString("CATEGORIA_titolo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Video.
        '''</summary>
        Public Shared ReadOnly Property CATEGORIA_video() As String
            Get
                Return ResourceManager.GetString("CATEGORIA_video", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Select the exact match from the results obtained from TheTVDB.com.
        '''</summary>
        Public Shared ReadOnly Property DLG_TVDB_Desc2() As String
            Get
                Return ResourceManager.GetString("DLG_TVDB_Desc2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Aperture value.
        '''</summary>
        Public Shared ReadOnly Property EXIF_ApertureValue() As String
            Get
                Return ResourceManager.GetString("EXIF_ApertureValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Brightness value.
        '''</summary>
        Public Shared ReadOnly Property EXIF_BrightnessValue() As String
            Get
                Return ResourceManager.GetString("EXIF_BrightnessValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Color space.
        '''</summary>
        Public Shared ReadOnly Property EXIF_ColorSpace() As String
            Get
                Return ResourceManager.GetString("EXIF_ColorSpace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Compressed BPP.
        '''</summary>
        Public Shared ReadOnly Property EXIF_CompressedBitPerPixel() As String
            Get
                Return ResourceManager.GetString("EXIF_CompressedBitPerPixel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a DateTime digitized.
        '''</summary>
        Public Shared ReadOnly Property EXIF_DateTimeDigitized() As String
            Get
                Return ResourceManager.GetString("EXIF_DateTimeDigitized", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a DateTime original.
        '''</summary>
        Public Shared ReadOnly Property EXIF_DateTimeOriginal() As String
            Get
                Return ResourceManager.GetString("EXIF_DateTimeOriginal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Digital zoom ratio.
        '''</summary>
        Public Shared ReadOnly Property EXIF_DigitalZoomRatio() As String
            Get
                Return ResourceManager.GetString("EXIF_DigitalZoomRatio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Exposure bias value.
        '''</summary>
        Public Shared ReadOnly Property EXIF_ExposureBiasValue() As String
            Get
                Return ResourceManager.GetString("EXIF_ExposureBiasValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Exposure mode.
        '''</summary>
        Public Shared ReadOnly Property EXIF_ExposureMode() As String
            Get
                Return ResourceManager.GetString("EXIF_ExposureMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Exposure time.
        '''</summary>
        Public Shared ReadOnly Property EXIF_ExposureTime() As String
            Get
                Return ResourceManager.GetString("EXIF_ExposureTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Flash.
        '''</summary>
        Public Shared ReadOnly Property EXIF_Flash() As String
            Get
                Return ResourceManager.GetString("EXIF_Flash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Flash energy BCPS.
        '''</summary>
        Public Shared ReadOnly Property EXIF_FlashEnergy() As String
            Get
                Return ResourceManager.GetString("EXIF_FlashEnergy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Focal length MM.
        '''</summary>
        Public Shared ReadOnly Property EXIF_FocalLenght() As String
            Get
                Return ResourceManager.GetString("EXIF_FocalLenght", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Artist.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_Artist() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_Artist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Compression.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_Compression() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_Compression", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Copyright.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_Copyright() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_Copyright", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Date.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_DateTime() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_DateTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Equipment model.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_EquipmentModel() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_EquipmentModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Image description.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_ImageDescription() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_ImageDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Image height.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_ImageHeight() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_ImageHeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Image width.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_ImageWidth() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_ImageWidth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Make.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_Make() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_Make", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Orientation.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_Orientation() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_Orientation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Horizontal.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_Orientation_Value_1() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_Orientation_Value_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Horizontal mirrored.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_Orientation_Value_2() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_Orientation_Value_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Vertical.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_Orientation_Value_3() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_Orientation_Value_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Vertical mirrored.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_Orientation_Value_4() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_Orientation_Value_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Left side.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_Orientation_Value_5() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_Orientation_Value_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Left side mirrored.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_Orientation_Value_6() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_Orientation_Value_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Right side.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_Orientation_Value_7() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_Orientation_Value_7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Right side mirrored.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_Orientation_Value_8() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_Orientation_Value_8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Resolution unit.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_ResolutionUnit() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_ResolutionUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Software.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_Software() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_Software", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a X Resolution.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_XResolution() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_XResolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Y Resolution.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MAIN_YResolution() As String
            Get
                Return ResourceManager.GetString("EXIF_MAIN_YResolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Max value openings.
        '''</summary>
        Public Shared ReadOnly Property EXIF_MaxApertureValue() As String
            Get
                Return ResourceManager.GetString("EXIF_MaxApertureValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Pixel X Dimension.
        '''</summary>
        Public Shared ReadOnly Property EXIF_PixelXDimension() As String
            Get
                Return ResourceManager.GetString("EXIF_PixelXDimension", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Pixel Y Dimension.
        '''</summary>
        Public Shared ReadOnly Property EXIF_PixelYDimension() As String
            Get
                Return ResourceManager.GetString("EXIF_PixelYDimension", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Saturation.
        '''</summary>
        Public Shared ReadOnly Property EXIF_Saturation() As String
            Get
                Return ResourceManager.GetString("EXIF_Saturation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Scene capture type.
        '''</summary>
        Public Shared ReadOnly Property EXIF_SceneCaptureType() As String
            Get
                Return ResourceManager.GetString("EXIF_SceneCaptureType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Sensing method.
        '''</summary>
        Public Shared ReadOnly Property EXIF_SensingMethod() As String
            Get
                Return ResourceManager.GetString("EXIF_SensingMethod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Sharpness.
        '''</summary>
        Public Shared ReadOnly Property EXIF_Sharpness() As String
            Get
                Return ResourceManager.GetString("EXIF_Sharpness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Shutter speed value.
        '''</summary>
        Public Shared ReadOnly Property EXIF_ShutterSpeedValue() As String
            Get
                Return ResourceManager.GetString("EXIF_ShutterSpeedValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a white balance.
        '''</summary>
        Public Shared ReadOnly Property EXIF_WhiteBalance() As String
            Get
                Return ResourceManager.GetString("EXIF_WhiteBalance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a [Extensions].
        '''</summary>
        Public Shared ReadOnly Property EXT_Opzioni() As String
            Get
                Return ResourceManager.GetString("EXT_Opzioni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Aspect ratio.
        '''</summary>
        Public Shared ReadOnly Property II_AspectRatio() As String
            Get
                Return ResourceManager.GetString("II_AspectRatio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Color depth.
        '''</summary>
        Public Shared ReadOnly Property II_BitsPerPixel() As String
            Get
                Return ResourceManager.GetString("II_BitsPerPixel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Size.
        '''</summary>
        Public Shared ReadOnly Property II_Dimensione() As String
            Get
                Return ResourceManager.GetString("II_Dimensione", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a DPI Resolution.
        '''</summary>
        Public Shared ReadOnly Property II_DPI() As String
            Get
                Return ResourceManager.GetString("II_DPI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Unique colors.
        '''</summary>
        Public Shared ReadOnly Property II_UniqueColors() As String
            Get
                Return ResourceManager.GetString("II_UniqueColors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Creator.
        '''</summary>
        Public Shared ReadOnly Property IPTC_ByLine() As String
            Get
                Return ResourceManager.GetString("IPTC_ByLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Job creator.
        '''</summary>
        Public Shared ReadOnly Property IPTC_ByLineTitle() As String
            Get
                Return ResourceManager.GetString("IPTC_ByLineTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Description.
        '''</summary>
        Public Shared ReadOnly Property IPTC_CaprionAbstract() As String
            Get
                Return ResourceManager.GetString("IPTC_CaprionAbstract", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Category.
        '''</summary>
        Public Shared ReadOnly Property IPTC_Category() As String
            Get
                Return ResourceManager.GetString("IPTC_Category", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a City.
        '''</summary>
        Public Shared ReadOnly Property IPTC_City() As String
            Get
                Return ResourceManager.GetString("IPTC_City", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Copyright notice.
        '''</summary>
        Public Shared ReadOnly Property IPTC_CopyrightNotice() As String
            Get
                Return ResourceManager.GetString("IPTC_CopyrightNotice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Country.
        '''</summary>
        Public Shared ReadOnly Property IPTC_CountryPrimaryLocationName() As String
            Get
                Return ResourceManager.GetString("IPTC_CountryPrimaryLocationName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Credit line.
        '''</summary>
        Public Shared ReadOnly Property IPTC_Credit() As String
            Get
                Return ResourceManager.GetString("IPTC_Credit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Date.
        '''</summary>
        Public Shared ReadOnly Property IPTC_DateCreated() As String
            Get
                Return ResourceManager.GetString("IPTC_DateCreated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Title.
        '''</summary>
        Public Shared ReadOnly Property IPTC_HeadLine() As String
            Get
                Return ResourceManager.GetString("IPTC_HeadLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Title.
        '''</summary>
        Public Shared ReadOnly Property IPTC_ObjectName() As String
            Get
                Return ResourceManager.GetString("IPTC_ObjectName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a ID process.
        '''</summary>
        Public Shared ReadOnly Property IPTC_OriginalTransmissionReference() As String
            Get
                Return ResourceManager.GetString("IPTC_OriginalTransmissionReference", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Province.
        '''</summary>
        Public Shared ReadOnly Property IPTC_ProvinceState() As String
            Get
                Return ResourceManager.GetString("IPTC_ProvinceState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Contact.
        '''</summary>
        Public Shared ReadOnly Property IPTC_Separator_Contact() As String
            Get
                Return ResourceManager.GetString("IPTC_Separator_Contact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Details.
        '''</summary>
        Public Shared ReadOnly Property IPTC_Separator_Details() As String
            Get
                Return ResourceManager.GetString("IPTC_Separator_Details", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a State.
        '''</summary>
        Public Shared ReadOnly Property IPTC_Separator_State() As String
            Get
                Return ResourceManager.GetString("IPTC_Separator_State", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Origin.
        '''</summary>
        Public Shared ReadOnly Property IPTC_Source() As String
            Get
                Return ResourceManager.GetString("IPTC_Source", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Instructions.
        '''</summary>
        Public Shared ReadOnly Property IPTC_SpecialInstructions() As String
            Get
                Return ResourceManager.GetString("IPTC_SpecialInstructions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Author description.
        '''</summary>
        Public Shared ReadOnly Property IPTC_WriterEditor() As String
            Get
                Return ResourceManager.GetString("IPTC_WriterEditor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Add field.
        '''</summary>
        Public Shared ReadOnly Property MenuAddInfo() As String
            Get
                Return ResourceManager.GetString("MenuAddInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Aspect ratio.
        '''</summary>
        Public Shared ReadOnly Property MI_AspectRatio() As String
            Get
                Return ResourceManager.GetString("MI_AspectRatio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Bit rate (Kbps).
        '''</summary>
        Public Shared ReadOnly Property MI_AudioBitRate() As String
            Get
                Return ResourceManager.GetString("MI_AudioBitRate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Length.
        '''</summary>
        Public Shared ReadOnly Property MI_AudioDurata() As String
            Get
                Return ResourceManager.GetString("MI_AudioDurata", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Frequency (Khz).
        '''</summary>
        Public Shared ReadOnly Property MI_AudioFrequenza() As String
            Get
                Return ResourceManager.GetString("MI_AudioFrequenza", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Bit rate mode.
        '''</summary>
        Public Shared ReadOnly Property MI_AudioModalitaBitRate() As String
            Get
                Return ResourceManager.GetString("MI_AudioModalitaBitRate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Number of channels.
        '''</summary>
        Public Shared ReadOnly Property MI_AudioNumeroCanali() As String
            Get
                Return ResourceManager.GetString("MI_AudioNumeroCanali", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Album title.
        '''</summary>
        Public Shared ReadOnly Property MI_AudioTagAlbum() As String
            Get
                Return ResourceManager.GetString("MI_AudioTagAlbum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Artist.
        '''</summary>
        Public Shared ReadOnly Property MI_AudioTagArtista() As String
            Get
                Return ResourceManager.GetString("MI_AudioTagArtista", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Compositor.
        '''</summary>
        Public Shared ReadOnly Property MI_AudioTagCompositore() As String
            Get
                Return ResourceManager.GetString("MI_AudioTagCompositore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Recorded date.
        '''</summary>
        Public Shared ReadOnly Property MI_AudioTagDataRegistrazione() As String
            Get
                Return ResourceManager.GetString("MI_AudioTagDataRegistrazione", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Released date.
        '''</summary>
        Public Shared ReadOnly Property MI_AudioTagDataRilascio() As String
            Get
                Return ResourceManager.GetString("MI_AudioTagDataRilascio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Genre.
        '''</summary>
        Public Shared ReadOnly Property MI_AudioTagGenere() As String
            Get
                Return ResourceManager.GetString("MI_AudioTagGenere", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Track number.
        '''</summary>
        Public Shared ReadOnly Property MI_AudioTagNumero() As String
            Get
                Return ResourceManager.GetString("MI_AudioTagNumero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Record label.
        '''</summary>
        Public Shared ReadOnly Property MI_AudioTagPubliscer() As String
            Get
                Return ResourceManager.GetString("MI_AudioTagPubliscer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Track title.
        '''</summary>
        Public Shared ReadOnly Property MI_AudioTagTitolo() As String
            Get
                Return ResourceManager.GetString("MI_AudioTagTitolo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Audio format.
        '''</summary>
        Public Shared ReadOnly Property MI_CodecAudio() As String
            Get
                Return ResourceManager.GetString("MI_CodecAudio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Audio format with language.
        '''</summary>
        Public Shared ReadOnly Property MI_CodecAudioLingua() As String
            Get
                Return ResourceManager.GetString("MI_CodecAudioLingua", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Video format.
        '''</summary>
        Public Shared ReadOnly Property MI_CodecVideo() As String
            Get
                Return ResourceManager.GetString("MI_CodecVideo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Length.
        '''</summary>
        Public Shared ReadOnly Property MI_Durata() As String
            Get
                Return ResourceManager.GetString("MI_Durata", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Encoded video library.
        '''</summary>
        Public Shared ReadOnly Property MI_EncodedLibraryName() As String
            Get
                Return ResourceManager.GetString("MI_EncodedLibraryName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Frame rate.
        '''</summary>
        Public Shared ReadOnly Property MI_FrameRate() As String
            Get
                Return ResourceManager.GetString("MI_FrameRate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Audio languages.
        '''</summary>
        Public Shared ReadOnly Property MI_Lingue() As String
            Get
                Return ResourceManager.GetString("MI_Lingue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Subtitle languages.
        '''</summary>
        Public Shared ReadOnly Property MI_LingueSottotitoli() As String
            Get
                Return ResourceManager.GetString("MI_LingueSottotitoli", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Resolution.
        '''</summary>
        Public Shared ReadOnly Property MI_RisoluzioneFilmato() As String
            Get
                Return ResourceManager.GetString("MI_RisoluzioneFilmato", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Encoding information.
        '''</summary>
        Public Shared ReadOnly Property MI_Separator_Codifica() As String
            Get
                Return ResourceManager.GetString("MI_Separator_Codifica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Number chapters.
        '''</summary>
        Public Shared ReadOnly Property MI_TotaleCapitoli() As String
            Get
                Return ResourceManager.GetString("MI_TotaleCapitoli", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Date created.
        '''</summary>
        Public Shared ReadOnly Property PF_DataCreazione() As String
            Get
                Return ResourceManager.GetString("PF_DataCreazione", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Last modified.
        '''</summary>
        Public Shared ReadOnly Property PF_DataUltimaModifica() As String
            Get
                Return ResourceManager.GetString("PF_DataUltimaModifica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Last accessed.
        '''</summary>
        Public Shared ReadOnly Property PF_DataUltimoAccesso() As String
            Get
                Return ResourceManager.GetString("PF_DataUltimoAccesso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Original filename.
        '''</summary>
        Public Shared ReadOnly Property PF_NomeFile() As String
            Get
                Return ResourceManager.GetString("PF_NomeFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Sequential text.
        '''</summary>
        Public Shared ReadOnly Property STD_ElencoSequenziale() As String
            Get
                Return ResourceManager.GetString("STD_ElencoSequenziale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Extension.
        '''</summary>
        Public Shared ReadOnly Property STD_Estensione() As String
            Get
                Return ResourceManager.GetString("STD_Estensione", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Filter from the filename.
        '''</summary>
        Public Shared ReadOnly Property STD_FiltraNomeFile() As String
            Get
                Return ResourceManager.GetString("STD_FiltraNomeFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Audio information.
        '''</summary>
        Public Shared ReadOnly Property STD_InfoAudio() As String
            Get
                Return ResourceManager.GetString("STD_InfoAudio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Exif camera information.
        '''</summary>
        Public Shared ReadOnly Property STD_InfoEXIFFotocamera() As String
            Get
                Return ResourceManager.GetString("STD_InfoEXIFFotocamera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Exif general information.
        '''</summary>
        Public Shared ReadOnly Property STD_InfoEXIFGeneriche() As String
            Get
                Return ResourceManager.GetString("STD_InfoEXIFGeneriche", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a ID3 Tag information.
        '''</summary>
        Public Shared ReadOnly Property STD_InfoID3Tag() As String
            Get
                Return ResourceManager.GetString("STD_InfoID3Tag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Image information.
        '''</summary>
        Public Shared ReadOnly Property STD_InfoImmagine() As String
            Get
                Return ResourceManager.GetString("STD_InfoImmagine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a IPTC information.
        '''</summary>
        Public Shared ReadOnly Property STD_InfoIPTC() As String
            Get
                Return ResourceManager.GetString("STD_InfoIPTC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Multimedia information.
        '''</summary>
        Public Shared ReadOnly Property STD_InfoMultimediali() As String
            Get
                Return ResourceManager.GetString("STD_InfoMultimediali", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Sequential numbering.
        '''</summary>
        Public Shared ReadOnly Property STD_NumerazioneSequenziale() As String
            Get
                Return ResourceManager.GetString("STD_NumerazioneSequenziale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a File properties.
        '''</summary>
        Public Shared ReadOnly Property STD_ProprietaFile() As String
            Get
                Return ResourceManager.GetString("STD_ProprietaFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Separator.
        '''</summary>
        Public Shared ReadOnly Property STD_Separatore() As String
            Get
                Return ResourceManager.GetString("STD_Separatore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Text.
        '''</summary>
        Public Shared ReadOnly Property STD_Testo() As String
            Get
                Return ResourceManager.GetString("STD_Testo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a The TVDB.
        '''</summary>
        Public Shared ReadOnly Property STD_TheTvdb() As String
            Get
                Return ResourceManager.GetString("STD_TheTvdb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Creator.
        '''</summary>
        Public Shared ReadOnly Property TVDB_Creator() As String
            Get
                Return ResourceManager.GetString("TVDB_Creator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a First aired.
        '''</summary>
        Public Shared ReadOnly Property TVDB_DataPrimaTv() As String
            Get
                Return ResourceManager.GetString("TVDB_DataPrimaTv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Director.
        '''</summary>
        Public Shared ReadOnly Property TVDB_Director() As String
            Get
                Return ResourceManager.GetString("TVDB_Director", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Gender.
        '''</summary>
        Public Shared ReadOnly Property TVDB_Genere() As String
            Get
                Return ResourceManager.GetString("TVDB_Genere", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Network.
        '''</summary>
        Public Shared ReadOnly Property TVDB_Network() As String
            Get
                Return ResourceManager.GetString("TVDB_Network", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Number of episodes.
        '''</summary>
        Public Shared ReadOnly Property TVDB_NumeroEpisodi() As String
            Get
                Return ResourceManager.GetString("TVDB_NumeroEpisodi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Number of seasons.
        '''</summary>
        Public Shared ReadOnly Property TVDB_NumeroStagioni() As String
            Get
                Return ResourceManager.GetString("TVDB_NumeroStagioni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Episode title.
        '''</summary>
        Public Shared ReadOnly Property TVDB_TitoloEpisodio() As String
            Get
                Return ResourceManager.GetString("TVDB_TitoloEpisodio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a TV show title.
        '''</summary>
        Public Shared ReadOnly Property TVDB_TitoloSerieTv() As String
            Get
                Return ResourceManager.GetString("TVDB_TitoloSerieTv", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
