'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Localization
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Resource_Common
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Autorinomina.Resource_Common", GetType(Resource_Common).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a episodes.
        '''</summary>
        Public Shared ReadOnly Property AR_Core_Episodes() As String
            Get
                Return ResourceManager.GetString("AR_Core_Episodes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Missing ID3 Tag metadata..
        '''</summary>
        Public Shared ReadOnly Property AR_Core_Error_ID3MetadataMissing() As String
            Get
                Return ResourceManager.GetString("AR_Core_Error_ID3MetadataMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Incomplete list of sequential text. Recheck..
        '''</summary>
        Public Shared ReadOnly Property AR_Core_Error_SeqTextIncomplete() As String
            Get
                Return ResourceManager.GetString("AR_Core_Error_SeqTextIncomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a There is a problem with The TvDB..
        '''</summary>
        Public Shared ReadOnly Property AR_Core_Error_TVDB_Error() As String
            Get
                Return ResourceManager.GetString("AR_Core_Error_TVDB_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Missing numbering of the DVD episodes in The TVDB..
        '''</summary>
        Public Shared ReadOnly Property AR_Core_Error_TVDB_InexistentDVDnumerazion() As String
            Get
                Return ResourceManager.GetString("AR_Core_Error_TVDB_InexistentDVDnumerazion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Open file error..
        '''</summary>
        Public Shared ReadOnly Property AR_Core_Immagini_OpenFileError() As String
            Get
                Return ResourceManager.GetString("AR_Core_Immagini_OpenFileError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Automatic choice.
        '''</summary>
        Public Shared ReadOnly Property AutomaticChoose() As String
            Get
                Return ResourceManager.GetString("AutomaticChoose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Add.
        '''</summary>
        Public Shared ReadOnly Property Btn_Add() As String
            Get
                Return ResourceManager.GetString("Btn_Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Add and create new.
        '''</summary>
        Public Shared ReadOnly Property Btn_AddNew() As String
            Get
                Return ResourceManager.GetString("Btn_AddNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Apply.
        '''</summary>
        Public Shared ReadOnly Property Btn_Apply() As String
            Get
                Return ResourceManager.GetString("Btn_Apply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Cancel.
        '''</summary>
        Public Shared ReadOnly Property Btn_Cancel() As String
            Get
                Return ResourceManager.GetString("Btn_Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Delete.
        '''</summary>
        Public Shared ReadOnly Property Btn_Delete() As String
            Get
                Return ResourceManager.GetString("Btn_Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Abort.
        '''</summary>
        Public Shared ReadOnly Property Btn_Interrupt() As String
            Get
                Return ResourceManager.GetString("Btn_Interrupt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Ok.
        '''</summary>
        Public Shared ReadOnly Property Btn_Ok() As String
            Get
                Return ResourceManager.GetString("Btn_Ok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Open.
        '''</summary>
        Public Shared ReadOnly Property Btn_Open() As String
            Get
                Return ResourceManager.GetString("Btn_Open", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Save.
        '''</summary>
        Public Shared ReadOnly Property Btn_Save() As String
            Get
                Return ResourceManager.GetString("Btn_Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Cancel (Esc).
        '''</summary>
        Public Shared ReadOnly Property CancelEsc() As String
            Get
                Return ResourceManager.GetString("CancelEsc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a State.
        '''</summary>
        Public Shared ReadOnly Property Desc_Status() As String
            Get
                Return ResourceManager.GetString("Desc_Status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a It has encountered the following error:.
        '''</summary>
        Public Shared ReadOnly Property Exception_General() As String
            Get
                Return ResourceManager.GetString("Exception_General", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Welcome to Autorinomina!\nFollow the quick guide to learn how to rename in just 3 steps.\n\nClick here to start (Esc to exit).
        '''</summary>
        Public Shared ReadOnly Property Guide_Step1() As String
            Get
                Return ResourceManager.GetString("Guide_Step1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Step 1\nSelect the matching category for the type of files to rename.\nFor example &quot;Category images&quot; to rename your photos.\n\nClick here to continue....
        '''</summary>
        Public Shared ReadOnly Property Guide_Step2() As String
            Get
                Return ResourceManager.GetString("Guide_Step2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Step 2\nDrag here your selected files to rename.\n\nClick here to continue....
        '''</summary>
        Public Shared ReadOnly Property Guide_Step3() As String
            Get
                Return ResourceManager.GetString("Guide_Step3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Step 3\nCostumize the text of your files.\nUse the &quot;+&quot; button to add new field information.\n\nClick here to continue....
        '''</summary>
        Public Shared ReadOnly Property Guide_Step4() As String
            Get
                Return ResourceManager.GetString("Guide_Step4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Congratulations! Now you are ready to rename!\nFor a detailed guide line please visit the web homepage\n\nClick here to close..
        '''</summary>
        Public Shared ReadOnly Property Guide_Step5() As String
            Get
                Return ResourceManager.GetString("Guide_Step5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Skip.
        '''</summary>
        Public Shared ReadOnly Property Salta() As String
            Get
                Return ResourceManager.GetString("Salta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a File already renamed.
        '''</summary>
        Public Shared ReadOnly Property StateFileInfo_AlreadyRenamed() As String
            Get
                Return ResourceManager.GetString("StateFileInfo_AlreadyRenamed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a File already restored.
        '''</summary>
        Public Shared ReadOnly Property StateFileInfo_AlreadyRestored() As String
            Get
                Return ResourceManager.GetString("StateFileInfo_AlreadyRestored", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a In the folder there is already a file by that name.
        '''</summary>
        Public Shared ReadOnly Property StateFileInfo_FileAlreadyExist() As String
            Get
                Return ResourceManager.GetString("StateFileInfo_FileAlreadyExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Another renamed file uses the same name.
        '''</summary>
        Public Shared ReadOnly Property StateFileInfo_FileAlreadyRenamedWith() As String
            Get
                Return ResourceManager.GetString("StateFileInfo_FileAlreadyRenamedWith", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Manually edited.
        '''</summary>
        Public Shared ReadOnly Property StateFileInfo_ManualEditing() As String
            Get
                Return ResourceManager.GetString("StateFileInfo_ManualEditing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Missing the target name.
        '''</summary>
        Public Shared ReadOnly Property StateFileInfo_NameMissing() As String
            Get
                Return ResourceManager.GetString("StateFileInfo_NameMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Preview not generated (from settings).
        '''</summary>
        Public Shared ReadOnly Property StateFileInfo_NoPreviewBySettings() As String
            Get
                Return ResourceManager.GetString("StateFileInfo_NoPreviewBySettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a The file is no longer present with this name.
        '''</summary>
        Public Shared ReadOnly Property StateFileInfo_NotExist() As String
            Get
                Return ResourceManager.GetString("StateFileInfo_NotExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Not renamed (from settings).
        '''</summary>
        Public Shared ReadOnly Property StateFileInfo_NotRenamed() As String
            Get
                Return ResourceManager.GetString("StateFileInfo_NotRenamed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Not renamed.
        '''</summary>
        Public Shared ReadOnly Property StateFileInfo_NotRenamedUserChoice() As String
            Get
                Return ResourceManager.GetString("StateFileInfo_NotRenamedUserChoice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Not restored (from settings).
        '''</summary>
        Public Shared ReadOnly Property StateFileInfo_NotRestored() As String
            Get
                Return ResourceManager.GetString("StateFileInfo_NotRestored", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Ready.
        '''</summary>
        Public Shared ReadOnly Property StateFileInfo_PreviewOK() As String
            Get
                Return ResourceManager.GetString("StateFileInfo_PreviewOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Renamed.
        '''</summary>
        Public Shared ReadOnly Property StateFileInfo_Renamed() As String
            Get
                Return ResourceManager.GetString("StateFileInfo_Renamed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Restored.
        '''</summary>
        Public Shared ReadOnly Property StateFileInfo_Restored() As String
            Get
                Return ResourceManager.GetString("StateFileInfo_Restored", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Skipped because the names are the same.
        '''</summary>
        Public Shared ReadOnly Property StateFileInfo_SkippedSameName() As String
            Get
                Return ResourceManager.GetString("StateFileInfo_SkippedSameName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Operation stopped by the user.
        '''</summary>
        Public Shared ReadOnly Property StateFileInfo_UserInterrupt() As String
            Get
                Return ResourceManager.GetString("StateFileInfo_UserInterrupt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a All.
        '''</summary>
        Public Shared ReadOnly Property Text_All() As String
            Get
                Return ResourceManager.GetString("Text_All", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Unable to paste the preset, there are errors in the code..
        '''</summary>
        Public Shared ReadOnly Property XMLStrutture_PasteError1() As String
            Get
                Return ResourceManager.GetString("XMLStrutture_PasteError1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Unable to paste the preset, wrong category..
        '''</summary>
        Public Shared ReadOnly Property XMLStrutture_PasteError2() As String
            Get
                Return ResourceManager.GetString("XMLStrutture_PasteError2", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
