'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Localization
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Resource_WND_ElencoSequenziale
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Autorinomina.Resource_WND_ElencoSequenziale", GetType(Resource_WND_ElencoSequenziale).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Clear.
        '''</summary>
        Public Shared ReadOnly Property Clear() As String
            Get
                Return ResourceManager.GetString("Clear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Create or edit the sequential text list.
        '''</summary>
        Public Shared ReadOnly Property Descrizione() As String
            Get
                Return ResourceManager.GetString("Descrizione", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a How it works: each lines of the text matches to a file exactly as ordered. For example the text of the third line will be copied into the file ordered for third. In order to use this feature you must add the field [Sequential text]..
        '''</summary>
        Public Shared ReadOnly Property Guida() As String
            Get
                Return ResourceManager.GetString("Guida", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Open a file.
        '''</summary>
        Public Shared ReadOnly Property OpenFile() As String
            Get
                Return ResourceManager.GetString("OpenFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Paste from table.
        '''</summary>
        Public Shared ReadOnly Property PasteFromWiki() As String
            Get
                Return ResourceManager.GetString("PasteFromWiki", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Write a list or alternatively open a file or paste a table..
        '''</summary>
        Public Shared ReadOnly Property Status_empty() As String
            Get
                Return ResourceManager.GetString("Status_empty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a The list is ready..
        '''</summary>
        Public Shared ReadOnly Property Status_full() As String
            Get
                Return ResourceManager.GetString("Status_full", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Need more {0} strings..
        '''</summary>
        Public Shared ReadOnly Property Status_missing() As String
            Get
                Return ResourceManager.GetString("Status_missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Impossible to determine, the file list is empty..
        '''</summary>
        Public Shared ReadOnly Property Status_nofile() As String
            Get
                Return ResourceManager.GetString("Status_nofile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a There are {0} excess lines. Correct the list..
        '''</summary>
        Public Shared ReadOnly Property Status_surplus() As String
            Get
                Return ResourceManager.GetString("Status_surplus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Sequential text list.
        '''</summary>
        Public Shared ReadOnly Property Titolo() As String
            Get
                Return ResourceManager.GetString("Titolo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a There are some problems, some text may not have been pasted..
        '''</summary>
        Public Shared ReadOnly Property WikiPaste_error() As String
            Get
                Return ResourceManager.GetString("WikiPaste_error", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
