'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Localization
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Resource_WND_Impostazioni
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Autorinomina.Resource_WND_Impostazioni", GetType(Resource_WND_Impostazioni).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Audio extensions.
        '''</summary>
        Public Shared ReadOnly Property Extensions_Audio() As String
            Get
                Return ResourceManager.GetString("Extensions_Audio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Each extension must be separated with a comma character &quot;,&quot; and should not be included at the end of the extensions.
        '''</summary>
        Public Shared ReadOnly Property Extensions_GuideDesc() As String
            Get
                Return ResourceManager.GetString("Extensions_GuideDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Images extensions.
        '''</summary>
        Public Shared ReadOnly Property Extensions_Images() As String
            Get
                Return ResourceManager.GetString("Extensions_Images", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Metadata images extensions.
        '''</summary>
        Public Shared ReadOnly Property Extensions_ImagesMetadata() As String
            Get
                Return ResourceManager.GetString("Extensions_ImagesMetadata", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Video extensions.
        '''</summary>
        Public Shared ReadOnly Property Extensions_Video() As String
            Get
                Return ResourceManager.GetString("Extensions_Video", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Warning! Changing extensions recognized by the software may lead to unexpected behavior and errors. Therefore i am not responsible for any damage caused by improper use of this function..
        '''</summary>
        Public Shared ReadOnly Property Extensions_WarningDesc() As String
            Get
                Return ResourceManager.GetString("Extensions_WarningDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Run an external software (on each renamed file).
        '''</summary>
        Public Shared ReadOnly Property ExternalSoftware() As String
            Get
                Return ResourceManager.GetString("ExternalSoftware", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Change path.
        '''</summary>
        Public Shared ReadOnly Property ExternalSoftware_ChangePath() As String
            Get
                Return ResourceManager.GetString("ExternalSoftware_ChangePath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Command line arguments.
        '''</summary>
        Public Shared ReadOnly Property ExternalSoftware_CommandLine() As String
            Get
                Return ResourceManager.GetString("ExternalSoftware_CommandLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a The &apos;@&apos; character will be replaced with the full path of the file.
        '''</summary>
        Public Shared ReadOnly Property ExternalSoftware_CommandLine_desc() As String
            Get
                Return ResourceManager.GetString("ExternalSoftware_CommandLine_desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Enable option.
        '''</summary>
        Public Shared ReadOnly Property ExternalSoftware_Enable() As String
            Get
                Return ResourceManager.GetString("ExternalSoftware_Enable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Executable path.
        '''</summary>
        Public Shared ReadOnly Property ExternalSoftware_ExePath() As String
            Get
                Return ResourceManager.GetString("ExternalSoftware_ExePath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Minimized mode.
        '''</summary>
        Public Shared ReadOnly Property ExternalSoftware_Minimized() As String
            Get
                Return ResourceManager.GetString("ExternalSoftware_Minimized", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Run.
        '''</summary>
        Public Shared ReadOnly Property ExternalSoftware_RunDesc() As String
            Get
                Return ResourceManager.GetString("ExternalSoftware_RunDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a On category.
        '''</summary>
        Public Shared ReadOnly Property ExternalSoftware_RunOnCategory() As String
            Get
                Return ResourceManager.GetString("ExternalSoftware_RunOnCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Checking files.
        '''</summary>
        Public Shared ReadOnly Property FilesVerification() As String
            Get
                Return ResourceManager.GetString("FilesVerification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a In the category &apos;General&apos; exclude extensions &apos;* .db&apos;.
        '''</summary>
        Public Shared ReadOnly Property FilesVerification_ExcludeDBFiles() As String
            Get
                Return ResourceManager.GetString("FilesVerification_ExcludeDBFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Include hidden files and folders.
        '''</summary>
        Public Shared ReadOnly Property FilesVerification_IncludeHiddenFiles() As String
            Get
                Return ResourceManager.GetString("FilesVerification_IncludeHiddenFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Recursive method explores all folders and subfolders.
        '''</summary>
        Public Shared ReadOnly Property FilesVerification_IncludeHiddenFiles_Desc() As String
            Get
                Return ResourceManager.GetString("FilesVerification_IncludeHiddenFiles_Desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Always bring the window on top when auto-capture of files end.
        '''</summary>
        Public Shared ReadOnly Property FilesVerification_WindowOnTop() As String
            Get
                Return ResourceManager.GetString("FilesVerification_WindowOnTop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Select the external software.
        '''</summary>
        Public Shared ReadOnly Property Msg_SelectExternalSoftware() As String
            Get
                Return ResourceManager.GetString("Msg_SelectExternalSoftware", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Miscellaneous.
        '''</summary>
        Public Shared ReadOnly Property OtherOptions() As String
            Get
                Return ResourceManager.GetString("OtherOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Disable warning message when editing extensions.
        '''</summary>
        Public Shared ReadOnly Property OtherOptions_DisableExtensionWarning() As String
            Get
                Return ResourceManager.GetString("OtherOptions_DisableExtensionWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Enable notifications for checking updates every.
        '''</summary>
        Public Shared ReadOnly Property OtherOptions_NotifyUpdates() As String
            Get
                Return ResourceManager.GetString("OtherOptions_NotifyUpdates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a days.
        '''</summary>
        Public Shared ReadOnly Property OtherOptions_NotifyUpdates_Days() As String
            Get
                Return ResourceManager.GetString("OtherOptions_NotifyUpdates_Days", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Preserve saved the setting &apos;Always on top&apos;.
        '''</summary>
        Public Shared ReadOnly Property OtherOptions_PermanentAlwaysOnTop() As String
            Get
                Return ResourceManager.GetString("OtherOptions_PermanentAlwaysOnTop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Preview with cross-checking of local files.
        '''</summary>
        Public Shared ReadOnly Property OtherOptions_PreviewCheckLocalFile() As String
            Get
                Return ResourceManager.GetString("OtherOptions_PreviewCheckLocalFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Extensions.
        '''</summary>
        Public Shared ReadOnly Property Tab_Extensions() As String
            Get
                Return ResourceManager.GetString("Tab_Extensions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a External software.
        '''</summary>
        Public Shared ReadOnly Property Tab_ExternalSoftware() As String
            Get
                Return ResourceManager.GetString("Tab_ExternalSoftware", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Miscellaneous.
        '''</summary>
        Public Shared ReadOnly Property Tab_OtherOptions() As String
            Get
                Return ResourceManager.GetString("Tab_OtherOptions", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
