'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Localization
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Resource_OpzioniAvanzate
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Autorinomina.Resource_OpzioniAvanzate", GetType(Resource_OpzioniAvanzate).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Do not rename when there is no ID3 Tag.
        '''</summary>
        Public Shared ReadOnly Property Audio_ID3Missing() As String
            Get
                Return ResourceManager.GetString("Audio_ID3Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Behavior for missing numbering &apos;Tag-track number&apos;.
        '''</summary>
        Public Shared ReadOnly Property Audio_NoTagNumber() As String
            Get
                Return ResourceManager.GetString("Audio_NoTagNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Do not include the numbering.
        '''</summary>
        Public Shared ReadOnly Property Audio_NoTagNumber_ExcludeNumeration() As String
            Get
                Return ResourceManager.GetString("Audio_NoTagNumber_ExcludeNumeration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Do not rename the file.
        '''</summary>
        Public Shared ReadOnly Property Audio_NoTagNumber_NoRename() As String
            Get
                Return ResourceManager.GetString("Audio_NoTagNumber_NoRename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Try to obtain it from the filename.
        '''</summary>
        Public Shared ReadOnly Property Audio_NoTagNumber_UseFilter() As String
            Get
                Return ResourceManager.GetString("Audio_NoTagNumber_UseFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Use the sequential numbering.
        '''</summary>
        Public Shared ReadOnly Property Audio_NoTagNumber_UseSequentialNumber() As String
            Get
                Return ResourceManager.GetString("Audio_NoTagNumber_UseSequentialNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Exclude any non-numeric characters in the &apos;Tag-track number&apos;.
        '''</summary>
        Public Shared ReadOnly Property Audio_TagNumber_ExcludeOtherChars() As String
            Get
                Return ResourceManager.GetString("Audio_TagNumber_ExcludeOtherChars", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Behavior for missing numbering.
        '''</summary>
        Public Shared ReadOnly Property Desc_NoNumberCase() As String
            Get
                Return ResourceManager.GetString("Desc_NoNumberCase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Miscellaneous options.
        '''</summary>
        Public Shared ReadOnly Property Desc_OtherOptions() As String
            Get
                Return ResourceManager.GetString("Desc_OtherOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Use reverse lookup to find the numbering.
        '''</summary>
        Public Shared ReadOnly Property Desc_ReverseSearchNumber() As String
            Get
                Return ResourceManager.GetString("Desc_ReverseSearchNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Remove pattern &apos;{0}&apos; ?.
        '''</summary>
        Public Shared ReadOnly Property Msg_DeletePatternRegex() As String
            Get
                Return ResourceManager.GetString("Msg_DeletePatternRegex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Enter regex pattern.
        '''</summary>
        Public Shared ReadOnly Property Msg_InsertPattern() As String
            Get
                Return ResourceManager.GetString("Msg_InsertPattern", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Enter any notes.
        '''</summary>
        Public Shared ReadOnly Property Msg_InsertPatternNote() As String
            Get
                Return ResourceManager.GetString("Msg_InsertPatternNote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Enter a filename (without extension).
        '''</summary>
        Public Shared ReadOnly Property Msg_PatternTest() As String
            Get
                Return ResourceManager.GetString("Msg_PatternTest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Empty the cache?.
        '''</summary>
        Public Shared ReadOnly Property Msg_TVDB_ClearCache() As String
            Get
                Return ResourceManager.GetString("Msg_TVDB_ClearCache", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Filter options.
        '''</summary>
        Public Shared ReadOnly Property OpzioniFiltro() As String
            Get
                Return ResourceManager.GetString("OpzioniFiltro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Delete brackets &apos;() []&apos; from the filename.
        '''</summary>
        Public Shared ReadOnly Property RemoveBracket() As String
            Get
                Return ResourceManager.GetString("RemoveBracket", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Convert roman to arabic numbers.
        '''</summary>
        Public Shared ReadOnly Property SerieTv_ConvertRomanNumbers() As String
            Get
                Return ResourceManager.GetString("SerieTv_ConvertRomanNumbers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Example (Part II) becomes (Part 2).
        '''</summary>
        Public Shared ReadOnly Property SerieTv_ConvertRomanNumbers_Tooltip() As String
            Get
                Return ResourceManager.GetString("SerieTv_ConvertRomanNumbers_Tooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Regex to recognize the numbering.
        '''</summary>
        Public Shared ReadOnly Property SerieTv_OpzioniFiltro_DescRegex() As String
            Get
                Return ResourceManager.GetString("SerieTv_OpzioniFiltro_DescRegex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Behavior in case of error.
        '''</summary>
        Public Shared ReadOnly Property SerieTv_OpzioniFiltro_Error() As String
            Get
                Return ResourceManager.GetString("SerieTv_OpzioniFiltro_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Ask to manually correct the filename.
        '''</summary>
        Public Shared ReadOnly Property SerieTv_OpzioniFiltro_Error_ManualFix() As String
            Get
                Return ResourceManager.GetString("SerieTv_OpzioniFiltro_Error_ManualFix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Do not rename.
        '''</summary>
        Public Shared ReadOnly Property SerieTv_OpzioniFiltro_Error_NoRename() As String
            Get
                Return ResourceManager.GetString("SerieTv_OpzioniFiltro_Error_NoRename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Execution mode.
        '''</summary>
        Public Shared ReadOnly Property SerieTv_OpzioniFiltro_Modalita() As String
            Get
                Return ResourceManager.GetString("SerieTv_OpzioniFiltro_Modalita", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Automatic.
        '''</summary>
        Public Shared ReadOnly Property SerieTv_OpzioniFiltro_Modalita_Auto() As String
            Get
                Return ResourceManager.GetString("SerieTv_OpzioniFiltro_Modalita_Auto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Allow filter choice.
        '''</summary>
        Public Shared ReadOnly Property SerieTv_OpzioniFiltro_Modalita_CanChoose() As String
            Get
                Return ResourceManager.GetString("SerieTv_OpzioniFiltro_Modalita_CanChoose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Allow filter choice only on error.
        '''</summary>
        Public Shared ReadOnly Property SerieTv_OpzioniFiltro_Modalita_OnlyOnError() As String
            Get
                Return ResourceManager.GetString("SerieTv_OpzioniFiltro_Modalita_OnlyOnError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Add pattern.
        '''</summary>
        Public Shared ReadOnly Property SerieTv_OpzioniFiltro_PatternAdd() As String
            Get
                Return ResourceManager.GetString("SerieTv_OpzioniFiltro_PatternAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Copy pattern.
        '''</summary>
        Public Shared ReadOnly Property SerieTv_OpzioniFiltro_PatternClipboard() As String
            Get
                Return ResourceManager.GetString("SerieTv_OpzioniFiltro_PatternClipboard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Delete pattern.
        '''</summary>
        Public Shared ReadOnly Property SerieTv_OpzioniFiltro_PatternDelete() As String
            Get
                Return ResourceManager.GetString("SerieTv_OpzioniFiltro_PatternDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Test pattern.
        '''</summary>
        Public Shared ReadOnly Property SerieTv_OpzioniFiltro_PatternTest() As String
            Get
                Return ResourceManager.GetString("SerieTv_OpzioniFiltro_PatternTest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Recognize numbering episodes linked.
        '''</summary>
        Public Shared ReadOnly Property SerieTv_OpzioniFiltro_RecognizeLinkedEpisode() As String
            Get
                Return ResourceManager.GetString("SerieTv_OpzioniFiltro_RecognizeLinkedEpisode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Example &quot;1x01-02&quot; if it is not necessary it is recommended to disable.
        '''</summary>
        Public Shared ReadOnly Property SerieTv_OpzioniFiltro_RecognizeLinkedEpisode_Tooltip() As String
            Get
                Return ResourceManager.GetString("SerieTv_OpzioniFiltro_RecognizeLinkedEpisode_Tooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Delete brackets &apos;() []&apos; from the episode title.
        '''</summary>
        Public Shared ReadOnly Property SerieTv_OpzioniFiltro_RemoveBracketEpisode() As String
            Get
                Return ResourceManager.GetString("SerieTv_OpzioniFiltro_RemoveBracketEpisode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Delete brackets &apos;() []&apos; from the title of the TV series.
        '''</summary>
        Public Shared ReadOnly Property SerieTv_OpzioniFiltro_RemoveBracketSeriesTitle() As String
            Get
                Return ResourceManager.GetString("SerieTv_OpzioniFiltro_RemoveBracketSeriesTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a The TVDB.
        '''</summary>
        Public Shared ReadOnly Property TabName_TheTvdb() As String
            Get
                Return ResourceManager.GetString("TabName_TheTvdb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a The seasons of the TV series are associated.
        '''</summary>
        Public Shared ReadOnly Property TVDB_AssociatedSeasons() As String
            Get
                Return ResourceManager.GetString("TVDB_AssociatedSeasons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a To aired season (default).
        '''</summary>
        Public Shared ReadOnly Property TVDB_AssociatedSeasons_0() As String
            Get
                Return ResourceManager.GetString("TVDB_AssociatedSeasons_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a To the DVD/BD.
        '''</summary>
        Public Shared ReadOnly Property TVDB_AssociatedSeasons_1() As String
            Get
                Return ResourceManager.GetString("TVDB_AssociatedSeasons_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a The services of The TVDB require a working internet connection.
        '''</summary>
        Public Shared ReadOnly Property TVDB_DescInfo() As String
            Get
                Return ResourceManager.GetString("TVDB_DescInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Languages used in research.
        '''</summary>
        Public Shared ReadOnly Property TVDB_Language_Desc() As String
            Get
                Return ResourceManager.GetString("TVDB_Language_Desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a When the episode title is missing in your chosen language, use the English language.
        '''</summary>
        Public Shared ReadOnly Property TVDB_Language_FallbackEnglish() As String
            Get
                Return ResourceManager.GetString("TVDB_Language_FallbackEnglish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Main language.
        '''</summary>
        Public Shared ReadOnly Property TVDB_Language_Main() As String
            Get
                Return ResourceManager.GetString("TVDB_Language_Main", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Secondary language.
        '''</summary>
        Public Shared ReadOnly Property TVDB_Language_Secondary() As String
            Get
                Return ResourceManager.GetString("TVDB_Language_Secondary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Reload languages.
        '''</summary>
        Public Shared ReadOnly Property TVDB_ReloadLanguages() As String
            Get
                Return ResourceManager.GetString("TVDB_ReloadLanguages", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Search options.
        '''</summary>
        Public Shared ReadOnly Property TVDB_ResearchOptions_Desc() As String
            Get
                Return ResourceManager.GetString("TVDB_ResearchOptions_Desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Search Mode.
        '''</summary>
        Public Shared ReadOnly Property TVDB_SearchMethod() As String
            Get
                Return ResourceManager.GetString("TVDB_SearchMethod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Automatic.
        '''</summary>
        Public Shared ReadOnly Property TVDB_SearchMethod_Auto() As String
            Get
                Return ResourceManager.GetString("TVDB_SearchMethod_Auto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Let me choose.
        '''</summary>
        Public Shared ReadOnly Property TVDB_SearchMethod_CanChoose() As String
            Get
                Return ResourceManager.GetString("TVDB_SearchMethod_CanChoose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a The automatic search mode in some cases might not give positive results..
        '''</summary>
        Public Shared ReadOnly Property TVDB_SearchMethod_Info() As String
            Get
                Return ResourceManager.GetString("TVDB_SearchMethod_Info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Behavior in case of no result.
        '''</summary>
        Public Shared ReadOnly Property TVDB_SearchNoResults() As String
            Get
                Return ResourceManager.GetString("TVDB_SearchNoResults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Use the filter.
        '''</summary>
        Public Shared ReadOnly Property TVDB_SearchNoResults_UseFilter() As String
            Get
                Return ResourceManager.GetString("TVDB_SearchNoResults_UseFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Use a less aggressive filtering.
        '''</summary>
        Public Shared ReadOnly Property WeakFilter() As String
            Get
                Return ResourceManager.GetString("WeakFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a It keeps text similar to the original text.
        '''</summary>
        Public Shared ReadOnly Property WeakFilter_Tooltip() As String
            Get
                Return ResourceManager.GetString("WeakFilter_Tooltip", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
