'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Localization
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Resource_WND_Termini
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Autorinomina.Resource_WND_Termini", GetType(Resource_WND_Termini).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a List of words in black-list by category.
        '''</summary>
        Public Shared ReadOnly Property BlackList_desc() As String
            Get
                Return ResourceManager.GetString("BlackList_desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Case sensitive/non sensitive.
        '''</summary>
        Public Shared ReadOnly Property Column_DistinguiMaiuscoleMinuscole() As String
            Get
                Return ResourceManager.GetString("Column_DistinguiMaiuscoleMinuscole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Word.
        '''</summary>
        Public Shared ReadOnly Property Column_Termine() As String
            Get
                Return ResourceManager.GetString("Column_Termine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Replace.
        '''</summary>
        Public Shared ReadOnly Property Column_TermineSostituisci() As String
            Get
                Return ResourceManager.GetString("Column_TermineSostituisci", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Order of words (the order of removal influences in the results).
        '''</summary>
        Public Shared ReadOnly Property Desc_SortTermini() As String
            Get
                Return ResourceManager.GetString("Desc_SortTermini", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a The &quot;▪&quot; characters represent the spaces at the beginning/end of a word.
        '''</summary>
        Public Shared ReadOnly Property Desc_SpecialChar() As String
            Get
                Return ResourceManager.GetString("Desc_SpecialChar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Remove word.
        '''</summary>
        Public Shared ReadOnly Property EliminaTermine() As String
            Get
                Return ResourceManager.GetString("EliminaTermine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Export words.
        '''</summary>
        Public Shared ReadOnly Property EsportaTermini() As String
            Get
                Return ResourceManager.GetString("EsportaTermini", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Import words.
        '''</summary>
        Public Shared ReadOnly Property ImportaTermini() As String
            Get
                Return ResourceManager.GetString("ImportaTermini", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Insert word.
        '''</summary>
        Public Shared ReadOnly Property InserisciTermine() As String
            Get
                Return ResourceManager.GetString("InserisciTermine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Export of words completed..
        '''</summary>
        Public Shared ReadOnly Property Msg_ExportFile() As String
            Get
                Return ResourceManager.GetString("Msg_ExportFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a File imported successfully.{0}Imported words:{1}Already existing words:{2}.
        '''</summary>
        Public Shared ReadOnly Property Msg_ImportFile() As String
            Get
                Return ResourceManager.GetString("Msg_ImportFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Do you want remove the selected words?.
        '''</summary>
        Public Shared ReadOnly Property Msg_RemoveSelected() As String
            Get
                Return ResourceManager.GetString("Msg_RemoveSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a List of words to be replace by category.
        '''</summary>
        Public Shared ReadOnly Property Sostituzioni_desc() As String
            Get
                Return ResourceManager.GetString("Sostituzioni_desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a     Automatic.
        '''</summary>
        Public Shared ReadOnly Property Switch_Automatic() As String
            Get
                Return ResourceManager.GetString("Switch_Automatic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a     Manual.
        '''</summary>
        Public Shared ReadOnly Property Switch_Manual() As String
            Get
                Return ResourceManager.GetString("Switch_Manual", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
