'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Localization
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Resource_BalloonToolTip
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Autorinomina.Resource_BalloonToolTip", GetType(Resource_BalloonToolTip).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Format not supported.
        '''</summary>
        Public Shared ReadOnly Property Error_FormatNotSupported() As String
            Get
                Return ResourceManager.GetString("Error_FormatNotSupported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Convert characters to.
        '''</summary>
        Public Shared ReadOnly Property Grid_Extensions_ConvertChars() As String
            Get
                Return ResourceManager.GetString("Grid_Extensions_ConvertChars", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Do not convert.
        '''</summary>
        Public Shared ReadOnly Property Grid_Extensions_ConvertChars_1() As String
            Get
                Return ResourceManager.GetString("Grid_Extensions_ConvertChars_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a lowercase.
        '''</summary>
        Public Shared ReadOnly Property Grid_Extensions_ConvertChars_2() As String
            Get
                Return ResourceManager.GetString("Grid_Extensions_ConvertChars_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a UPPERCASE.
        '''</summary>
        Public Shared ReadOnly Property Grid_Extensions_ConvertChars_3() As String
            Get
                Return ResourceManager.GetString("Grid_Extensions_ConvertChars_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Enable options.
        '''</summary>
        Public Shared ReadOnly Property Grid_Extensions_EnableOptions() As String
            Get
                Return ResourceManager.GetString("Grid_Extensions_EnableOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Replace extensions with.
        '''</summary>
        Public Shared ReadOnly Property Grid_Extensions_ReplaceWith() As String
            Get
                Return ResourceManager.GetString("Grid_Extensions_ReplaceWith", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Warning! Change the extension of the files is a procedure that could make the file unusable\nUse it only if you are aware of the risks..
        '''</summary>
        Public Shared ReadOnly Property Grid_Extensions_Warning() As String
            Get
                Return ResourceManager.GetString("Grid_Extensions_Warning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Date and Time format.
        '''</summary>
        Public Shared ReadOnly Property Grid_FormatDateTime() As String
            Get
                Return ResourceManager.GetString("Grid_FormatDateTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a MM-dd-yy.
        '''</summary>
        Public Shared ReadOnly Property Grid_FormatDateTime_Ex1() As String
            Get
                Return ResourceManager.GetString("Grid_FormatDateTime_Ex1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a MM-dd-yyyy.
        '''</summary>
        Public Shared ReadOnly Property Grid_FormatDateTime_Ex2() As String
            Get
                Return ResourceManager.GetString("Grid_FormatDateTime_Ex2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a MM-dd-yy HH.mm.
        '''</summary>
        Public Shared ReadOnly Property Grid_FormatDateTime_Ex3() As String
            Get
                Return ResourceManager.GetString("Grid_FormatDateTime_Ex3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a MM-dd-yyyy HH.mm.
        '''</summary>
        Public Shared ReadOnly Property Grid_FormatDateTime_Ex4() As String
            Get
                Return ResourceManager.GetString("Grid_FormatDateTime_Ex4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a MMMM-dddd-yyyy.
        '''</summary>
        Public Shared ReadOnly Property Grid_FormatDateTime_Ex5() As String
            Get
                Return ResourceManager.GetString("Grid_FormatDateTime_Ex5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Time format.
        '''</summary>
        Public Shared ReadOnly Property Grid_FormatLenght_TimeFormat() As String
            Get
                Return ResourceManager.GetString("Grid_FormatLenght_TimeFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a %H.%M.
        '''</summary>
        Public Shared ReadOnly Property Grid_FormatLenght_TimeFormat_Ex1() As String
            Get
                Return ResourceManager.GetString("Grid_FormatLenght_TimeFormat_Ex1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a %H,%M.
        '''</summary>
        Public Shared ReadOnly Property Grid_FormatLenght_TimeFormat_Ex2() As String
            Get
                Return ResourceManager.GetString("Grid_FormatLenght_TimeFormat_Ex2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a %Mm %Ss.
        '''</summary>
        Public Shared ReadOnly Property Grid_FormatLenght_TimeFormat_Ex3() As String
            Get
                Return ResourceManager.GetString("Grid_FormatLenght_TimeFormat_Ex3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a %Mmin %Ssec.
        '''</summary>
        Public Shared ReadOnly Property Grid_FormatLenght_TimeFormat_Ex4() As String
            Get
                Return ResourceManager.GetString("Grid_FormatLenght_TimeFormat_Ex4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a %M minuts %S seconds.
        '''</summary>
        Public Shared ReadOnly Property Grid_FormatLenght_TimeFormat_Ex5() As String
            Get
                Return ResourceManager.GetString("Grid_FormatLenght_TimeFormat_Ex5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Keep seconds.
        '''</summary>
        Public Shared ReadOnly Property Grid_FormatLenght_TimeFormat_WithSeconds() As String
            Get
                Return ResourceManager.GetString("Grid_FormatLenght_TimeFormat_WithSeconds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Auto leading zeros.
        '''</summary>
        Public Shared ReadOnly Property Grid_NumSeq_AutoPadding() As String
            Get
                Return ResourceManager.GetString("Grid_NumSeq_AutoPadding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Numbering parameters.
        '''</summary>
        Public Shared ReadOnly Property Grid_NumSeq_Desc() As String
            Get
                Return ResourceManager.GetString("Grid_NumSeq_Desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Episode number.
        '''</summary>
        Public Shared ReadOnly Property Grid_NumSeq_NumEpisodio() As String
            Get
                Return ResourceManager.GetString("Grid_NumSeq_NumEpisodio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Start from.
        '''</summary>
        Public Shared ReadOnly Property Grid_NumSeq_NumEpisodio_IniziaDa() As String
            Get
                Return ResourceManager.GetString("Grid_NumSeq_NumEpisodio_IniziaDa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Season number.
        '''</summary>
        Public Shared ReadOnly Property Grid_NumSeq_NumStag() As String
            Get
                Return ResourceManager.GetString("Grid_NumSeq_NumStag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Prefix.
        '''</summary>
        Public Shared ReadOnly Property Grid_NumSeq_Prefisso() As String
            Get
                Return ResourceManager.GetString("Grid_NumSeq_Prefisso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Suffix.
        '''</summary>
        Public Shared ReadOnly Property Grid_NumSeq_Suffisso() As String
            Get
                Return ResourceManager.GetString("Grid_NumSeq_Suffisso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Pattern.
        '''</summary>
        Public Shared ReadOnly Property Grid_RegexPattern_Desc() As String
            Get
                Return ResourceManager.GetString("Grid_RegexPattern_Desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Instead of inserting remove the information.
        '''</summary>
        Public Shared ReadOnly Property Grid_RemoveInsteadInsert() As String
            Get
                Return ResourceManager.GetString("Grid_RemoveInsteadInsert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Add spacing.
        '''</summary>
        Public Shared ReadOnly Property Grid_Separator_AddSpace() As String
            Get
                Return ResourceManager.GetString("Grid_Separator_AddSpace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a With spacing [Pelide - achille.avi] without [Pelide-achille.avi].
        '''</summary>
        Public Shared ReadOnly Property Grid_Separator_AddSpace_Tooltip() As String
            Get
                Return ResourceManager.GetString("Grid_Separator_AddSpace_Tooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Apply to all.
        '''</summary>
        Public Shared ReadOnly Property Grid_Separator_Btn_ApplyToAll() As String
            Get
                Return ResourceManager.GetString("Grid_Separator_Btn_ApplyToAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Character.
        '''</summary>
        Public Shared ReadOnly Property Grid_Separator_Desc() As String
            Get
                Return ResourceManager.GetString("Grid_Separator_Desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Numbering style.
        '''</summary>
        Public Shared ReadOnly Property Grid_StileNumerazione_CB_StileNumerazione() As String
            Get
                Return ResourceManager.GetString("Grid_StileNumerazione_CB_StileNumerazione", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Normal\t\t\t[1,2,3 ... 11,12,13].
        '''</summary>
        Public Shared ReadOnly Property Grid_StileNumerazione_CB_StileNumerazione_0() As String
            Get
                Return ResourceManager.GetString("Grid_StileNumerazione_CB_StileNumerazione_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Normal with zeros\t[01,02,03 ... 11,12,13].
        '''</summary>
        Public Shared ReadOnly Property Grid_StileNumerazione_CB_StileNumerazione_1() As String
            Get
                Return ResourceManager.GetString("Grid_StileNumerazione_CB_StileNumerazione_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Roman\t\t\t[I, II, III ... XI, XII, XIII].
        '''</summary>
        Public Shared ReadOnly Property Grid_StileNumerazione_CB_StileNumerazione_2() As String
            Get
                Return ResourceManager.GetString("Grid_StileNumerazione_CB_StileNumerazione_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Alphabetical\t\t[A, B, C ... AA, AB, AC].
        '''</summary>
        Public Shared ReadOnly Property Grid_StileNumerazione_CB_StileNumerazione_3() As String
            Get
                Return ResourceManager.GetString("Grid_StileNumerazione_CB_StileNumerazione_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Alphabetical alt.\t\t[A, B, C ... AA, BB, CC].
        '''</summary>
        Public Shared ReadOnly Property Grid_StileNumerazione_CB_StileNumerazione_4() As String
            Get
                Return ResourceManager.GetString("Grid_StileNumerazione_CB_StileNumerazione_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Tv Series - European\t[1x01].
        '''</summary>
        Public Shared ReadOnly Property Grid_StileNumerazione_CB_StileNumerazione_5() As String
            Get
                Return ResourceManager.GetString("Grid_StileNumerazione_CB_StileNumerazione_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Tv Series - European alt.\t[1.01].
        '''</summary>
        Public Shared ReadOnly Property Grid_StileNumerazione_CB_StileNumerazione_6() As String
            Get
                Return ResourceManager.GetString("Grid_StileNumerazione_CB_StileNumerazione_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Tv Series - American\t[S01E01].
        '''</summary>
        Public Shared ReadOnly Property Grid_StileNumerazione_CB_StileNumerazione_7() As String
            Get
                Return ResourceManager.GetString("Grid_StileNumerazione_CB_StileNumerazione_7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Tv Series - Numeric\t[101].
        '''</summary>
        Public Shared ReadOnly Property Grid_StileNumerazione_CB_StileNumerazione_8() As String
            Get
                Return ResourceManager.GetString("Grid_StileNumerazione_CB_StileNumerazione_8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Format.
        '''</summary>
        Public Shared ReadOnly Property Grid_StyleSize_Format() As String
            Get
                Return ResourceManager.GetString("Grid_StyleSize_Format", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a %Wx%H.
        '''</summary>
        Public Shared ReadOnly Property Grid_StyleSize_Format_Ex1() As String
            Get
                Return ResourceManager.GetString("Grid_StyleSize_Format_Ex1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Rounds values.
        '''</summary>
        Public Shared ReadOnly Property Grid_StyleSize_RoundedValues() As String
            Get
                Return ResourceManager.GetString("Grid_StyleSize_RoundedValues", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Edit.
        '''</summary>
        Public Shared ReadOnly Property Grid_Text_Desc() As String
            Get
                Return ResourceManager.GetString("Grid_Text_Desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Concatenate text parts.
        '''</summary>
        Public Shared ReadOnly Property Grid_TitleEpisode_Concatenate() As String
            Get
                Return ResourceManager.GetString("Grid_TitleEpisode_Concatenate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Activate only in case of missing parts of the text in the title of the TV series.
        '''</summary>
        Public Shared ReadOnly Property Grid_TitleEpisode_ConcatenateDesc() As String
            Get
                Return ResourceManager.GetString("Grid_TitleEpisode_ConcatenateDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Reorder episodes.
        '''</summary>
        Public Shared ReadOnly Property Grid_TVDB_OrderEpisode() As String
            Get
                Return ResourceManager.GetString("Grid_TVDB_OrderEpisode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Default order.
        '''</summary>
        Public Shared ReadOnly Property Grid_TVDB_OrderEpisode_1() As String
            Get
                Return ResourceManager.GetString("Grid_TVDB_OrderEpisode_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a DVD/BD order.
        '''</summary>
        Public Shared ReadOnly Property Grid_TVDB_OrderEpisode_2() As String
            Get
                Return ResourceManager.GetString("Grid_TVDB_OrderEpisode_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a DVD/BD order (plus combined episodes).
        '''</summary>
        Public Shared ReadOnly Property Grid_TVDB_OrderEpisode_3() As String
            Get
                Return ResourceManager.GetString("Grid_TVDB_OrderEpisode_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a DVD/BD order (combined with all the titles).
        '''</summary>
        Public Shared ReadOnly Property Grid_TVDB_OrderEpisode_4() As String
            Get
                Return ResourceManager.GetString("Grid_TVDB_OrderEpisode_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Unit of measure.
        '''</summary>
        Public Shared ReadOnly Property Grid_UnitMeasure() As String
            Get
                Return ResourceManager.GetString("Grid_UnitMeasure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Pixel.
        '''</summary>
        Public Shared ReadOnly Property Grid_UnitMeasure_Type1() As String
            Get
                Return ResourceManager.GetString("Grid_UnitMeasure_Type1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Millimeters.
        '''</summary>
        Public Shared ReadOnly Property Grid_UnitMeasure_Type2() As String
            Get
                Return ResourceManager.GetString("Grid_UnitMeasure_Type2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Centimeters.
        '''</summary>
        Public Shared ReadOnly Property Grid_UnitMeasure_Type3() As String
            Get
                Return ResourceManager.GetString("Grid_UnitMeasure_Type3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Inches.
        '''</summary>
        Public Shared ReadOnly Property Grid_UnitMeasure_Type4() As String
            Get
                Return ResourceManager.GetString("Grid_UnitMeasure_Type4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Remove all.
        '''</summary>
        Public Shared ReadOnly Property GridModifica_Btn_RemoveAllInfo() As String
            Get
                Return ResourceManager.GetString("GridModifica_Btn_RemoveAllInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Remove field.
        '''</summary>
        Public Shared ReadOnly Property GridModifica_Btn_RemoveInfo() As String
            Get
                Return ResourceManager.GetString("GridModifica_Btn_RemoveInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Example:.
        '''</summary>
        Public Shared ReadOnly Property Text_Example() As String
            Get
                Return ResourceManager.GetString("Text_Example", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Numbering from the filter.
        '''</summary>
        Public Shared ReadOnly Property Title_ByFilter() As String
            Get
                Return ResourceManager.GetString("Title_ByFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a DPI Options.
        '''</summary>
        Public Shared ReadOnly Property Title_DPIOptions() As String
            Get
                Return ResourceManager.GetString("Title_DPIOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Edit extensions.
        '''</summary>
        Public Shared ReadOnly Property Title_Extensions() As String
            Get
                Return ResourceManager.GetString("Title_Extensions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Date format.
        '''</summary>
        Public Shared ReadOnly Property Title_FormatDateTime() As String
            Get
                Return ResourceManager.GetString("Title_FormatDateTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Time format.
        '''</summary>
        Public Shared ReadOnly Property Title_FormatLenght() As String
            Get
                Return ResourceManager.GetString("Title_FormatLenght", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Sequential numbering.
        '''</summary>
        Public Shared ReadOnly Property Title_NumSeq() As String
            Get
                Return ResourceManager.GetString("Title_NumSeq", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Regular expression.
        '''</summary>
        Public Shared ReadOnly Property Title_RegexPattern() As String
            Get
                Return ResourceManager.GetString("Title_RegexPattern", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Text delimiter.
        '''</summary>
        Public Shared ReadOnly Property Title_Separator() As String
            Get
                Return ResourceManager.GetString("Title_Separator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Text from list.
        '''</summary>
        Public Shared ReadOnly Property Title_SeqList() As String
            Get
                Return ResourceManager.GetString("Title_SeqList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Size options.
        '''</summary>
        Public Shared ReadOnly Property Title_SizeOptions() As String
            Get
                Return ResourceManager.GetString("Title_SizeOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Text box.
        '''</summary>
        Public Shared ReadOnly Property Title_TextBox() As String
            Get
                Return ResourceManager.GetString("Title_TextBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Episode title.
        '''</summary>
        Public Shared ReadOnly Property Title_TitleOfEpisode() As String
            Get
                Return ResourceManager.GetString("Title_TitleOfEpisode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Episode title.
        '''</summary>
        Public Shared ReadOnly Property Title_TVDB_TitleOfEpisode() As String
            Get
                Return ResourceManager.GetString("Title_TVDB_TitleOfEpisode", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
