'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Localization
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Resource_Common_Dialogs
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Autorinomina.Resource_Common_Dialogs", GetType(Resource_Common_Dialogs).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Text.
        '''</summary>
        Public Shared ReadOnly Property DLG_AddText_Desc() As String
            Get
                Return ResourceManager.GetString("DLG_AddText_Desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Add text.
        '''</summary>
        Public Shared ReadOnly Property DLG_AddText_Title() As String
            Get
                Return ResourceManager.GetString("DLG_AddText_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Select the folders containing the files to be renamed.
        '''</summary>
        Public Shared ReadOnly Property DLG_FavoriteFolder_Desc() As String
            Get
                Return ResourceManager.GetString("DLG_FavoriteFolder_Desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a There is no folder in this path, click on the &apos;Change path&apos; button..
        '''</summary>
        Public Shared ReadOnly Property DLG_FavoriteFolder_EmptyFolder() As String
            Get
                Return ResourceManager.GetString("DLG_FavoriteFolder_EmptyFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Select the folder containing files/sub-folders..
        '''</summary>
        Public Shared ReadOnly Property DLG_FavoriteFolder_Msg_ChangePath() As String
            Get
                Return ResourceManager.GetString("DLG_FavoriteFolder_Msg_ChangePath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Add folder.
        '''</summary>
        Public Shared ReadOnly Property DLG_FavoriteFolder_RowTextFolder() As String
            Get
                Return ResourceManager.GetString("DLG_FavoriteFolder_RowTextFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Add subfolder.
        '''</summary>
        Public Shared ReadOnly Property DLG_FavoriteFolder_RowTextSubfolder() As String
            Get
                Return ResourceManager.GetString("DLG_FavoriteFolder_RowTextSubfolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Add files from folder.
        '''</summary>
        Public Shared ReadOnly Property DLG_FavoriteFolder_Title() As String
            Get
                Return ResourceManager.GetString("DLG_FavoriteFolder_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Ignore this file (do not rename).
        '''</summary>
        Public Shared ReadOnly Property DLG_FileEsistente_Btn_Ignore() As String
            Get
                Return ResourceManager.GetString("DLG_FileEsistente_Btn_Ignore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Keep both files.
        '''</summary>
        Public Shared ReadOnly Property DLG_FileEsistente_Btn_KeepBoth() As String
            Get
                Return ResourceManager.GetString("DLG_FileEsistente_Btn_KeepBoth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a The files to be renamed, will be renamed to:.
        '''</summary>
        Public Shared ReadOnly Property DLG_FileEsistente_Btn_KeepBoth_Desc() As String
            Get
                Return ResourceManager.GetString("DLG_FileEsistente_Btn_KeepBoth_Desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Replace files in the destination.
        '''</summary>
        Public Shared ReadOnly Property DLG_FileEsistente_Btn_Replace() As String
            Get
                Return ResourceManager.GetString("DLG_FileEsistente_Btn_Replace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a This path already contains a file named.
        '''</summary>
        Public Shared ReadOnly Property DLG_FileEsistente_Desc() As String
            Get
                Return ResourceManager.GetString("DLG_FileEsistente_Desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Replace or ignores.
        '''</summary>
        Public Shared ReadOnly Property DLG_FileEsistente_Title() As String
            Get
                Return ResourceManager.GetString("DLG_FileEsistente_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a TIP: The space is any character..
        '''</summary>
        Public Shared ReadOnly Property DLG_InsertTermine_BlackList_Tips() As String
            Get
                Return ResourceManager.GetString("DLG_InsertTermine_BlackList_Tips", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Distinguish upper case/lower case.
        '''</summary>
        Public Shared ReadOnly Property DLG_InsertTermine_DistinctionCase() As String
            Get
                Return ResourceManager.GetString("DLG_InsertTermine_DistinctionCase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Inactive.
        '''</summary>
        Public Shared ReadOnly Property DLG_InsertTermine_DistinctionCase_Disabled() As String
            Get
                Return ResourceManager.GetString("DLG_InsertTermine_DistinctionCase_Disabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Active.
        '''</summary>
        Public Shared ReadOnly Property DLG_InsertTermine_DistinctionCase_Enabled() As String
            Get
                Return ResourceManager.GetString("DLG_InsertTermine_DistinctionCase_Enabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Word name.
        '''</summary>
        Public Shared ReadOnly Property DLG_InsertTermine_Name() As String
            Get
                Return ResourceManager.GetString("DLG_InsertTermine_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Replace with.
        '''</summary>
        Public Shared ReadOnly Property DLG_InsertTermine_ReplaceWith() As String
            Get
                Return ResourceManager.GetString("DLG_InsertTermine_ReplaceWith", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a TIP: If it is necessary also include the space before/after the word..
        '''</summary>
        Public Shared ReadOnly Property DLG_InsertTermine_Substitutions_Tips() As String
            Get
                Return ResourceManager.GetString("DLG_InsertTermine_Substitutions_Tips", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Existing word!.
        '''</summary>
        Public Shared ReadOnly Property DLG_InsertTermine_TermineAlreadyExists() As String
            Get
                Return ResourceManager.GetString("DLG_InsertTermine_TermineAlreadyExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Apply the filter on each file.
        '''</summary>
        Public Shared ReadOnly Property DLG_ManualFilter_ApplyToAll() As String
            Get
                Return ResourceManager.GetString("DLG_ManualFilter_ApplyToAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Select the most correct result filtered.
        '''</summary>
        Public Shared ReadOnly Property DLG_ManualFilter_Desc1() As String
            Get
                Return ResourceManager.GetString("DLG_ManualFilter_Desc1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Path:.
        '''</summary>
        Public Shared ReadOnly Property DLG_ManualFilter_FilePath() As String
            Get
                Return ResourceManager.GetString("DLG_ManualFilter_FilePath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Size.
        '''</summary>
        Public Shared ReadOnly Property DLG_ManualFilter_FileSize() As String
            Get
                Return ResourceManager.GetString("DLG_ManualFilter_FileSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a It was not possible to apply the filters..
        '''</summary>
        Public Shared ReadOnly Property DLG_ManualFilter_NoResults() As String
            Get
                Return ResourceManager.GetString("DLG_ManualFilter_NoResults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Filter selection.
        '''</summary>
        Public Shared ReadOnly Property DLG_ManualFilter_Title() As String
            Get
                Return ResourceManager.GetString("DLG_ManualFilter_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a It was not possible to filter the filename..
        '''</summary>
        Public Shared ReadOnly Property DLG_ManualRename_Desc() As String
            Get
                Return ResourceManager.GetString("DLG_ManualRename_Desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Write the new name of the file (by omitting the extension):.
        '''</summary>
        Public Shared ReadOnly Property DLG_ManualRename_Desc2() As String
            Get
                Return ResourceManager.GetString("DLG_ManualRename_Desc2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Manually change the filename.
        '''</summary>
        Public Shared ReadOnly Property DLG_ManualRename_Title() As String
            Get
                Return ResourceManager.GetString("DLG_ManualRename_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Select the column header to be pasted.
        '''</summary>
        Public Shared ReadOnly Property DLG_PasteWiki_Desc() As String
            Get
                Return ResourceManager.GetString("DLG_PasteWiki_Desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Do not paste the column header.
        '''</summary>
        Public Shared ReadOnly Property DLG_PasteWiki_NoPasteColumnHeader() As String
            Get
                Return ResourceManager.GetString("DLG_PasteWiki_NoPasteColumnHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Select the column header to be pasted..
        '''</summary>
        Public Shared ReadOnly Property DLG_PasteWiki_SelectHeaderColumn() As String
            Get
                Return ResourceManager.GetString("DLG_PasteWiki_SelectHeaderColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Delete the preset?.
        '''</summary>
        Public Shared ReadOnly Property DLG_Presets_DeletePreset() As String
            Get
                Return ResourceManager.GetString("DLG_Presets_DeletePreset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a You have to give a name to the presets.
        '''</summary>
        Public Shared ReadOnly Property DLG_Presets_NeedPresetName() As String
            Get
                Return ResourceManager.GetString("DLG_Presets_NeedPresetName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Overwrite the existing preset?.
        '''</summary>
        Public Shared ReadOnly Property DLG_Presets_OverwritePreset() As String
            Get
                Return ResourceManager.GetString("DLG_Presets_OverwritePreset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Preset name.
        '''</summary>
        Public Shared ReadOnly Property DLG_Presets_PresetName() As String
            Get
                Return ResourceManager.GetString("DLG_Presets_PresetName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a You must select a preset..
        '''</summary>
        Public Shared ReadOnly Property DLG_Presets_SelectPreset() As String
            Get
                Return ResourceManager.GetString("DLG_Presets_SelectPreset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Load preset.
        '''</summary>
        Public Shared ReadOnly Property DLG_Presets_Title_Load() As String
            Get
                Return ResourceManager.GetString("DLG_Presets_Title_Load", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Save preset.
        '''</summary>
        Public Shared ReadOnly Property DLG_Presets_Title_Save() As String
            Get
                Return ResourceManager.GetString("DLG_Presets_Title_Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Preview processing in progress….
        '''</summary>
        Public Shared ReadOnly Property DLG_Preview_Desc() As String
            Get
                Return ResourceManager.GetString("DLG_Preview_Desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a initialization....
        '''</summary>
        Public Shared ReadOnly Property DLG_Rename_Desc_Initialize() As String
            Get
                Return ResourceManager.GetString("DLG_Rename_Desc_Initialize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a The process of renaming is in progress....
        '''</summary>
        Public Shared ReadOnly Property DLG_Rename_Desc_Rename() As String
            Get
                Return ResourceManager.GetString("DLG_Rename_Desc_Rename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a The process of restoring is in progress....
        '''</summary>
        Public Shared ReadOnly Property DLG_Rename_Desc_Restore() As String
            Get
                Return ResourceManager.GetString("DLG_Rename_Desc_Restore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Close.
        '''</summary>
        Public Shared ReadOnly Property DLG_Riepilogo_Btn_Close() As String
            Get
                Return ResourceManager.GetString("DLG_Riepilogo_Btn_Close", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a View results.
        '''</summary>
        Public Shared ReadOnly Property DLG_Riepilogo_Btn_ViewResults() As String
            Get
                Return ResourceManager.GetString("DLG_Riepilogo_Btn_ViewResults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Summary of file restore operations.
        '''</summary>
        Public Shared ReadOnly Property DLG_Riepilogo_Desc1() As String
            Get
                Return ResourceManager.GetString("DLG_Riepilogo_Desc1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Summary of file renaming operations.
        '''</summary>
        Public Shared ReadOnly Property DLG_Riepilogo_Desc2() As String
            Get
                Return ResourceManager.GetString("DLG_Riepilogo_Desc2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a It is recommended to check the results.
        '''</summary>
        Public Shared ReadOnly Property DLG_Riepilogo_Desc3() As String
            Get
                Return ResourceManager.GetString("DLG_Riepilogo_Desc3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Summary preview process of files.
        '''</summary>
        Public Shared ReadOnly Property DLG_Riepilogo_Desc4() As String
            Get
                Return ResourceManager.GetString("DLG_Riepilogo_Desc4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Files with correct preview.
        '''</summary>
        Public Shared ReadOnly Property DLG_Riepilogo_PreviewMsg1() As String
            Get
                Return ResourceManager.GetString("DLG_Riepilogo_PreviewMsg1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Files without preview for errors.
        '''</summary>
        Public Shared ReadOnly Property DLG_Riepilogo_PreviewMsg2() As String
            Get
                Return ResourceManager.GetString("DLG_Riepilogo_PreviewMsg2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Files in conflict with others.
        '''</summary>
        Public Shared ReadOnly Property DLG_Riepilogo_PreviewMsg3() As String
            Get
                Return ResourceManager.GetString("DLG_Riepilogo_PreviewMsg3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Files without preview (from settings).
        '''</summary>
        Public Shared ReadOnly Property DLG_Riepilogo_PreviewMsg4() As String
            Get
                Return ResourceManager.GetString("DLG_Riepilogo_PreviewMsg4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Renamed files.
        '''</summary>
        Public Shared ReadOnly Property DLG_Riepilogo_RenameMsg1() As String
            Get
                Return ResourceManager.GetString("DLG_Riepilogo_RenameMsg1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Not renamed files (user choice).
        '''</summary>
        Public Shared ReadOnly Property DLG_Riepilogo_RenameMsg2() As String
            Get
                Return ResourceManager.GetString("DLG_Riepilogo_RenameMsg2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Not renamed files (from settings).
        '''</summary>
        Public Shared ReadOnly Property DLG_Riepilogo_RenameMsg3() As String
            Get
                Return ResourceManager.GetString("DLG_Riepilogo_RenameMsg3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Files in conflict with others.
        '''</summary>
        Public Shared ReadOnly Property DLG_Riepilogo_RenameMsg4() As String
            Get
                Return ResourceManager.GetString("DLG_Riepilogo_RenameMsg4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Files not renamed for errors.
        '''</summary>
        Public Shared ReadOnly Property DLG_Riepilogo_RenameMsg5() As String
            Get
                Return ResourceManager.GetString("DLG_Riepilogo_RenameMsg5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Restored files.
        '''</summary>
        Public Shared ReadOnly Property DLG_Riepilogo_RestoreMsg1() As String
            Get
                Return ResourceManager.GetString("DLG_Riepilogo_RestoreMsg1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Not restored files (user choice).
        '''</summary>
        Public Shared ReadOnly Property DLG_Riepilogo_RestoreMsg2() As String
            Get
                Return ResourceManager.GetString("DLG_Riepilogo_RestoreMsg2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Not restored files (from settings).
        '''</summary>
        Public Shared ReadOnly Property DLG_Riepilogo_RestoreMsg3() As String
            Get
                Return ResourceManager.GetString("DLG_Riepilogo_RestoreMsg3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Files in conflict with others.
        '''</summary>
        Public Shared ReadOnly Property DLG_Riepilogo_RestoreMsg4() As String
            Get
                Return ResourceManager.GetString("DLG_Riepilogo_RestoreMsg4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Files not restored for errors.
        '''</summary>
        Public Shared ReadOnly Property DLG_Riepilogo_RestoreMsg5() As String
            Get
                Return ResourceManager.GetString("DLG_Riepilogo_RestoreMsg5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Operation summary.
        '''</summary>
        Public Shared ReadOnly Property DLG_Riepilogo_Title() As String
            Get
                Return ResourceManager.GetString("DLG_Riepilogo_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Search.
        '''</summary>
        Public Shared ReadOnly Property DLG_TVDB_Btn_Find() As String
            Get
                Return ResourceManager.GetString("DLG_TVDB_Btn_Find", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Originally aired.
        '''</summary>
        Public Shared ReadOnly Property DLG_TVDB_Column_FirstAired() As String
            Get
                Return ResourceManager.GetString("DLG_TVDB_Column_FirstAired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Language.
        '''</summary>
        Public Shared ReadOnly Property DLG_TVDB_Column_Language() As String
            Get
                Return ResourceManager.GetString("DLG_TVDB_Column_Language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Network.
        '''</summary>
        Public Shared ReadOnly Property DLG_TVDB_Column_Network() As String
            Get
                Return ResourceManager.GetString("DLG_TVDB_Column_Network", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Title Series TV.
        '''</summary>
        Public Shared ReadOnly Property DLG_TVDB_Column_TitleSeries() As String
            Get
                Return ResourceManager.GetString("DLG_TVDB_Column_TitleSeries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Looking for Tv Series:.
        '''</summary>
        Public Shared ReadOnly Property DLG_TVDB_Desc1() As String
            Get
                Return ResourceManager.GetString("DLG_TVDB_Desc1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a If the search has not produced the expected results, start a new search:.
        '''</summary>
        Public Shared ReadOnly Property DLG_TVDB_Desc2() As String
            Get
                Return ResourceManager.GetString("DLG_TVDB_Desc2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Word to search.
        '''</summary>
        Public Shared ReadOnly Property DLG_TVDB_Desc3() As String
            Get
                Return ResourceManager.GetString("DLG_TVDB_Desc3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Searching ... .
        '''</summary>
        Public Shared ReadOnly Property DLG_TVDB_Desc4() As String
            Get
                Return ResourceManager.GetString("DLG_TVDB_Desc4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Select a result..
        '''</summary>
        Public Shared ReadOnly Property DLG_TVDB_Msg_SelectResult() As String
            Get
                Return ResourceManager.GetString("DLG_TVDB_Msg_SelectResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a The search did not yield any results.
        '''</summary>
        Public Shared ReadOnly Property DLG_TVDB_NoResults() As String
            Get
                Return ResourceManager.GetString("DLG_TVDB_NoResults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Associate results from TheTVDB.com.
        '''</summary>
        Public Shared ReadOnly Property DLG_TVDB_Title() As String
            Get
                Return ResourceManager.GetString("DLG_TVDB_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Checking files in progress....
        '''</summary>
        Public Shared ReadOnly Property DLG_VerificationFiles_Desc() As String
            Get
                Return ResourceManager.GetString("DLG_VerificationFiles_Desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Added files can not be renamed with the current category.\nSelect the correct category..
        '''</summary>
        Public Shared ReadOnly Property DLG_VerificationFiles_WrongCategory() As String
            Get
                Return ResourceManager.GetString("DLG_VerificationFiles_WrongCategory", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
